# Generated by Django 3.2.19 on 2023-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
