# Generated by Django 3.2.19 on 2023-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrapicore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
