# Generated by Django 3.2.19 on 2023-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrapicore', '0002_auto_20230607_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
