# Generated by Django 3.2.19 on 2023-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrapicore', '0003_auto_20230609_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='colour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrate',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
