# Generated by Django 3.2.18 on 2023-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrapibase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
